# Generated by Django 6.0.5 on 2026-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meetup_spot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='meetup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
