# Generated by Django 6.0.5 on 2026-06-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_message_meetup_spot_message_meetup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='meetup_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
