# Generated by Django 6.0.5 on 2026-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
