# Generated by Django 6.0.5 on 2026-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings_app', '0002_listing_listing_type_listing_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('sold', 'Sold'), ('boosted', 'Boosted')], default='active', max_length=20),
        ),
    ]
